### ISSUE TITLE
prevent creation of duplicate entries

### ISSUE THREAD

**Issue by LiohMoeller** [nicolascb/nsshconfig#2]
right now I can create a new entry:

nssh add testserver1 root@localhost

multiple times. Is it possible to check if a label with this name already exists and prevent the creation of the duplicate entry?

**Comment by nicolascb** [comment]
Hello @MarcusMoeller ,

This is already done, check it out here ([actions.go](https://github.com/nicolascb/nssh/blob/master/actions.go#L75))

Example:

![image](https://user-images.githubusercontent.com/1793185/55802004-b5f3b300-5aad-11e9-8505-d5f8e805e3e2.png)

Is not working for you?

**Comment by LiohMoeller** [comment]
$ nssh add localhost root@localhost
✔ OK: Successfully added host [localhost]
$ nssh add localhost root@localhost
✔ OK: Successfully added host [localhost]
$ nssh add localhost root@localhost
✔ OK: Successfully added host [localhost]
$ nssh list
List:
	local -> root@localhost:22
	local -> root@localhost:22
	local -> root@localhost:22

**Comment by nicolascb** [comment]
This happens when there is the word "host" in the alias.

It's a bug, I'll fix it.

**Comment by nicolascb** [comment]
@MarcusMoeller,

Please, check now: [1.0.4](https://github.com/nicolascb/nssh/releases/tag/1.0.4)
